name: Deploy to GH Pages

on:
  push:
    branches: [test-dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: public
